### ISSUE TITLE
Feedback - Session May 20

### ISSUE THREAD

**Issue by mvdam** [code-star/typescript-101#15]
- [x] - Slide wijden aan type infer? 
- [x]   ```
- [x]     if (value === undefined)
- [x]       // here I know I'm not T
- [x]     else
- [x]       // here I know I'm not undefined
- [x]   ```
- [x] - "Write first TS slide": simpeler maken, mss `code .` eruit halen, cross platform commandos gebruiken? document.write gebruiken ipv console log om het wat simpeler te maken? We moesten best wel wat tijd spenderen aan het uitleggen hiervan
- [x] - Update solution 1 obv nieuwe exercise 1
- [x] - Is het "leuk" om de nadelen van TS te benoemen? Bijv het `@types` ecosystem, type clashing e.d.?
- [x] - Is de content over classes etc echt relevant? Misschien inkorten?
- [x] - In Repo readme zetten hoe lang deze cursus is (1 / 2 dagdelen)

**Comment by Bjeaurn** [comment]
Hele sterke punten, ik zou wat betreft de oefeningen misschien het TSC deel wel willen benoemen, maar voor de rest gewoon uitwijken naar de TypeScript playground misschien?
